### ISSUE TITLE
Some symbols do not render with the stock font 

### ISSUE THREAD

**Issue by arl** [aurelien-rainone/tmux-gitbar#10]
This is what is shown on Linux with the Fixed font, using tmux Powerline:
![image](https://cloud.githubusercontent.com/assets/476650/13203259/a6dc5cf6-d8b4-11e5-9d0b-8ef831a2b7c2.png)

![image](https://cloud.githubusercontent.com/assets/476650/13203261/b0f51d86-d8b4-11e5-8e68-6c3329953db6.png)

If this is only the branch symbol that doesn't show up, I guess the default would be to not have it displayed.  
However, if there are too many symbols that don't show up in a vanilla configuration, the set of symbols should be changed.

**Comment by adrianluff** [comment]
Using the Unicode symbol ⎇ ( u8997 ) would be a viable alternative for the branch symbol. This would eliminate the dependency on the powerline font hack.

**Comment by arl** [comment]
Did you have some problems with the default symbols? if yes, which symbol(s), which font and OS are you using?
Thanks for reporting ;-)

**Comment by adrianluff** [comment]
I don't want to use the hack-y powerline fonts. I'm on Mac OS X 10.11.5. The branch symbol was the only default symbol that wasn't visible by default. I updated my `tmux-gitbar.conf` with:
`BRANCH_SYMBOL="⎇";`
...so problem solved for me. This seems like a viable Unicode alternative to the Powerline symbol for general usage though.

**Comment by thurt** [comment]
Same experience as @adrianluff -- I followed his fix

**Comment by arl** [comment]
The default should work out of the box on a vanilla configuration. If you confirm to me that the only symbol that doesn't show up correctly on a default Mac OS X configuration, I'll use another one as the default and set up a variable to change the default (for powerline users) that will be disabled by default

**Comment by thurt** [comment]
@aurelien-rainone that is the only symbol I have noticed that doesn't show. I am on Ubuntu 14.04 lxterminal using default monospace font

**Comment by arl** [comment]
Ok great. Thanks for the confirmation.

**Comment by arl** [comment]
Should be fixed by #29
I'll close if and when one of you tried and tell me it's ok

**Comment by adrianluff** [comment]
Looks good!

**Comment by arl** [comment]
closing, fixed by #29 and confirmed
