### ISSUE TITLE
Unnecessarily overwriting status-left or right

### ISSUE THREAD

**Issue by adrianluff** [aurelien-rainone/tmux-gitbar#28]
Presently tmux-gitbar overwrites the entire status-left or status-right tmux configuration. While the default status line is restored this limitation restricts TMGB's utility.

Consider `tmux-gitbar.sh` line 176:

``` bash
tmux set-window-option -a "status-$TMGB_STATUS_LOCATION" "$status_string" > /dev/null
```

replaced with:

``` bash
tmux set-window-option "status-$TMGB_STATUS_LOCATION" "$TMGB_OUTREPO_STATUS" > /dev/null
tmux set-window-option -a "status-$TMGB_STATUS_LOCATION" "$status_string" > /dev/null
```

The new behavior is to restore the default each time, then ADD (-a) the TMGB information to the user's existing tmux status line.

**Comment by arl** [comment]
Hi Adrian, thank for your input, that seems legit.
FYI i took the initiative to split this issue into two different ones because they are not directly dependent, so i edit your issue text and copied the second part into #30

For current issue, I'll have a look into it to see if there can't be side effects, though i guess not.

**Comment by arl** [comment]
Ok, i created PR #31 to fix this issue. Previous statuses are not overwritten anymore.
Thanks for the input again. Basically i'm appending the tmgb status to the previous one, after having also restored the out-of-repo style, meaning that different style should coexist on the same part of the tmux status bar. Before merging this PR, I'd be very happy to hear about you @adrianluff  and know if there are any side effects.

**Comment by adrianluff** [comment]
The only issue I've observed running with this for the last few weeks is an occasional visible screen redraw when tmux updates the status line twice in quick succession. That seems like a tmux issue though. 

I will update with the latest PRs and report back as soon as I'm able.

**Comment by arl** [comment]
Great!

**Comment by arl** [comment]
I just thought about the issue you are talking about, it's probably the
consequence of the two successive calls to set-window-option, both triggers
a status line redraw. In my PR I didn't think of that and will update it
accordingly, strings concatenation should be performed in bash where
possible and the result sent to tmux, triggering an unique status redraw

**Comment by adrianluff** [comment]
I was able to test your pull request for this issue. Works great here!

**Comment by arl** [comment]
Closing, #30 has been merged into master
