### ISSUE TITLE
How does tmux-gitbar would take advantage of tmux v2.3

### ISSUE THREAD

**Issue by arl** [aurelien-rainone/tmux-gitbar#35]
tmux v2.3 has been released, with a nice [changelog's](https://raw.githubusercontent.com/tmux/tmux/master/CHANGES) .

How could tmux-gitbar take advantage of the new tmux features, especially from:
- New option 'pane-border-status' to add text in the pane borders.
- Support for hooks on commands: 'after' and 'before' hooks.

Switching from one pane to another, or from a window to another would immediately update git status. This removes the need to modify bash's PROMPT_COMMAND. This would also make tmux-gitbar shell-independent.

At this point, installation with the tmux-plugins-manager would be super easy.

**Comment by evantravers** [comment]
👍

**Comment by aurelien-rainone** [comment]
don't have much time to work on that for now, though it shouldn't be too difficultto do.
a PR would be welcome ;-)

**Comment by arl** [comment]
This is done in [github.com/arl/gitmux](https://github.com/arl/gitmux)
