### ISSUE TITLE
tmux-gitbar.conf needs to exist outside the repo

### ISSUE THREAD

**Issue by alexkornitzer** [aurelien-rainone/tmux-gitbar#37]
Could you allow the option to have the tmux-gitbar.conf exist outside the repo? Apologies if this functionality already exists. Having the file exist in the repo makes it difficult to maintain the file across systems. I have tmux-gitbar as a submodule in my home folder setup which means I cannot manage the tmux-gitbar.conf across my machines. The conf file should really exist in the home folder anyway: ~/.tmux-gitbar.conf

**Comment by arl** [comment]
Hi Alex. I understand your problem, but in the currently state of things, i
dont think you can have it versioned without modifying tmux git bar code.
Why dont you fork it and allow a different path to tmux-gitbar.conf?  In
case its not good enough for you i May resolve this when i have a bit of
time

**Comment by alexkornitzer** [comment]
Hi Aurelien. If you are okay with me applying the changes I am happy to have a go at implementing this. Would you want me to PR back into the project or is this not the sort of feature you would want. If so what level would you want it at hardcoded to HOME or completely user definable?

**Comment by arl** [comment]
Thanks, a PR would be great! It believe it would be nice to have a sensible default for the config file location (in `$HOME`) that remains overridable by the user. Currently, `tmux.gitbar.conf` is auto-generated if it's not found in the project root directory.

**Comment by alexkornitzer** [comment]
Awesome, already on the case. I nearly have it working so expect a PR soonish!

**Comment by arl** [comment]
Just have a look at the unit and integration test suite to be sure to not
break nothing😉. But dont bother run them locally, they will be be run on
Travis as soon as you open the PR. Cheers

**Comment by arl** [comment]
fixed in #38
