### ISSUE TITLE
Gitbar is squashed in to rightmost 14 characters

### ISSUE THREAD

**Issue by biot023** [aurelien-rainone/tmux-gitbar#43]
Hi -- I'm running the latest version of tmux, and the output is squashed over to the last 14 characters of the bottom bar.
This means that I'm not seeing anything but the truncated name of the branch I'm on.
Is there a configuration setting somewhere that I can alter to fix this?
Thanks for any & all help,
   Doug.

**Comment by arl** [comment]
Hi

It seems to me that a tmux setting is limiting the length of your status
bar. Did you have a look at the troobleshooting section?
https://github.com/aurelien-rainone/tmux-gitbar/blob/master/README.md#tmux-gitbar-doesnt-show-up-entirely

If that doesn't fix it, could you post here your `tmux.conf` (and
`tmgb.conf` in case you don't have the default one)

Cheers

**Comment by biot023** [comment]
The trouble-shooting page sorted it, cheers -- I hadn't spotted that, sorry.
Thanks again.

**Comment by arl** [comment]
Happy to hear that.
No problem
