### ISSUE TITLE
unknown option: status-right-style

### ISSUE THREAD

**Issue by smazur** [aurelien-rainone/tmux-gitbar#53]
Got following message with tmux 1.8 and gitbar is not updating.

> unknown option: status-right-style

**Comment by arl** [comment]
Hi and thanks for reporting but tmux-gitbar does not support tmux 1.8, that is quite an old version you are using. Tmux-gitbar is tested and works with any tmux version from 1.9a included. Current tmux version is 2.6.

If however updating tmux is not an option and you really want to use tmux-gitbar, you can still do it but you'll have to modify tmux-gitbar code yourself. Cheers

**Comment by smazur** [comment]
I've workaround this issue by  kicking of the line causing this problem in ~/.tmux-gitbar/lib/tmux-gitbar.sh:69. So I assume the fix should be simple.

**Comment by arl** [comment]
By removing this line, tmux-gitbar won't be able to set the tmux status bar back to its _non-git_ state, by _non-git state_ I mean what tmux shows when your current directory is not a Git working tree. If you don't have a specially crafted tmux status bar, I guess that's not a problem.

**Comment by smazur** [comment]
Sorry for my bad explanation. I didn't removed it, but set TMGB_OUTREPO_STYLE to empty value. I didn't get any problems when switching between git/non-git directories. The only thing gitbar is not updated when i switching between tmux tabs.

**Comment by arl** [comment]
Oh ok. gitbar is never updated when switching between tmux windows, that is not related to what you did. Because the bar is updated via bash [`$PROMPT_COMMAND`](https://www.tldp.org/HOWTO/Bash-Prompt-HOWTO/x264.html), switching windows doesn't trigger `$PROMPT_COMMAND`.

Feel free to close this issue when you think it's resolved.
