### ISSUE TITLE
Bug when reading a newly created repo

### ISSUE THREAD

**Issue by willianpaixao** [aurelien-rainone/tmux-gitbar#54]
I noticed that if you enter a folder and hit `git init`, gitbar seems to have no code handle for having the git folder but no commits. Here follow my log:

```

/home/willian/.tmux-gitbar/lib/tmux-gitbar.sh: line 128: test: on: integer expression expected        
/home/willian/.tmux-gitbar/lib/tmux-gitbar.sh: line 128: test: master: integer expression expected    
/home/willian/.tmux-gitbar/lib/tmux-gitbar.sh: line 128: test: _NO_REMOTE_TRACKING_: integer expression expected                                                                                            
/home/willian/.tmux-gitbar/lib/tmux-gitbar.sh: line 128: test: ^: integer expression expected
```

Am I right? I could fix this issue if necessary. Just wanted to confirm with you guys before.

**Comment by arl** [comment]
Hi Willian,
You are very welcome to contribute with a PR for this issue. If you do so,
please  add tests checking the feature. Depending on the case, a unit
and/or an integration test case might suit better.

You should not need to install anything locally to run the tests, Travis-ci
will do all for you on code push, as it's especially uneasy to run
integration tests locally with TCL/expect, etc.


Thanks a lot
Cheers

**Comment by willianpaixao** [comment]
Ok, I get back to you soon.

**Comment by arl** [comment]
FYI this is basically the same issue than #52. I'll close the other issue
and keep the one you opened.

**Comment by savorywatt** [comment]
This error is also happening on a fresh install of Ubuntu LTS 18.04 with the versions listed below.

tmux 2.6
bash 4.4.19

It appears to happen on every command to the shell as well, regardless of if I am in a directory with git related information or not. I eyeballed the tmux-gitbar.sh and it is something in that 128 if block that is freaking out. Bash is not my strong suite so I could not debug further.

```
ls
```

```
cd
```
all cause it.

**Comment by arl** [comment]
Ok thanks for reporting

**Comment by ghost** [comment]
I can confirm what @savorywatt said. I'm seeing the same thing under the same setup.

**Comment by arl** [comment]
Ok. I believe this could be caused by tmux V2.6. not sure though. Can
anybody having that issue check if it is different with tmux 2.5 or lower?

**Comment by arl** [comment]
I just tried out with tmux tip (2.7) and I can't reproduce this behavior. I see something strange still, tmux git bar still shows git information of the previously entered git directory, it shouldn't. I'm not sure it might be related though. Anyway I'm going to investigate the issue you reported.
