### ISSUE TITLE
Git information not showing up after reloading tmux config

### ISSUE THREAD

**Issue by dhoss** [aurelien-rainone/tmux-gitbar#62]
I've installed tmux-gitbar by `git clone`-ing per the documentation, updated my config and run `source ~/.tmux.conf`.

Something initially suspect was that it seems to have hung on generating the git info (apologies, I don't have the exact message handy).  I had a config error unrelated to this that I fixed, and reloaded the config again with no change (it didn't hang this time, but no git information is being displayed in my tmux toolbar).

So, an itemized list of steps I've taken to get here:

1. install per documentation
2. update tmux config and reload
3. correct unrelated config error and reload
4. reload config several more times to attempt to fix issue

I've also tried running `update-gitbar` from the tmux command prompt but it tells me `Unknown command: update-gitbar`.  I'm not sure if it's because I'm calling it incorrectly or there's something else afoot.

I'm running under bash on high sierra.

bash version:
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin17)
Copyright (C) 2007 Free Software Foundation, Inc.

tmux version: tmux 2.7

.tmux.conf:
```
# remap prefix to Control + a
set -g prefix C-a
# bind 'C-a C-a' to type 'C-a'
bind C-a send-prefix
unbind C-b

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @continuum-restore 'on'

source-file "$HOME/.tmux-gitbar/tmux-gitbar.tmux"
# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
```

**Comment by arl** [comment]
Things that you could try to find the problem (in no particular order):
 - ensure all your tmux sessions are terminated (you can use `kill` or `tmux kill-server`) and then restart a new session
- run `update-gitbar` with its full path. If tmux-gitbar has been correctly installed and nothing messes with your tmux.conf. you should see something in tmux status bar.
- try with a vanilla tmux.conf to see if any or the TPM plugins conflict with tmux-gitbar

**Comment by arl** [comment]
Did you fix it?

**Comment by dhoss** [comment]
I'll try this again today, I've got a new set up so maybe it will elucidate my issue

**Comment by arl** [comment]
Did you fix so I can close the issue?

**Comment by dhoss** [comment]
sorry for keeping you waiting, go ahead and close this, I haven't been using it.

**Comment by arl** [comment]
No worries.
