### ISSUE TITLE
Make installable with Tmux Plugin Manager

### ISSUE THREAD

**Issue by arl** [aurelien-rainone/tmux-gitbar#8]
It should be relatively easy to adapt tmux-gitbar nomenclature to let it follow the one of a [tmux plugin manager](https://github.com/tmux-plugins/tpm) plugin.  
However, the fact that the `update_gitbar` callback needs to be added to `$PROMPT_COMMAND` from the user `.bashrc` could be a problem as adding one line to `tmux.conf` is not enough to make it work, there would still exist the need, as long as #9 is not solved, for an extra manual user action

**Comment by arl** [comment]
As **tmux-gitbar** would still require the user to manually add a line to its `.tmux.conf`, the fact is that there is little to no value (just complications) to make its installation 100 automated using TPM. Closing

**Comment by waigx** [comment]
Hi Aurélien, for 

> still require the user to manually add a line to its .tmux.conf,

 Do you mean the config line of `status-right` string?

**Comment by arl** [comment]
Hi @waigx.
The fact is tmux-gitbar, to function properly, requires a modification to the user's PROMPT_COMMAND environment variable.
If tmux-gitbar is installed to a location that is known beforehand (ex: $HOME/. tmux-gitbar) then it should be theory installable with TPM, because all what remains to be done is, as you said, configuring status-left|right.

If the installation location is different, then the user needs either to modify PROMPT_COMMAND via .bashrc, or via a line in .tmux.conf ( as stated in the docs)

All this makes it difficult with TPM.

However since tmux 2.2 I believe, hooks are supported, by using hooks tmux-gitbar wouldn't require any more to use PROMPT_COMMAND, as such, it would support all shells (as opposed to only bash for now)

This plus the fact that I rewrote a tool that provided the same features  as tmux-gitbar, in Go, using tmux hooks feature.
Have a look at #60
